### ISSUE TITLE
thank you for your code!

### ISSUE THREAD

**Issue by Zhang-O** [yang81/TextDetect#2]
Do you have any comparison with other text detection method in some open source dataset?

**Comment by yang81** [comment]
I'm happy my code is useful to u. For the speed, it's same to EAST , ( vgg net implement is slower than PVA Net implement), better than TextMountain, cause TextMountain use Opencv's minAreaRect; for the acc, i have not do it yet, i need a powerfull gpu for trainning models on different dataset.

**Comment by Zhang-O** [comment]
Got it! thanks for your job again!
